### ISSUE TITLE
errors while running the app

### ISSUE THREAD

**Issue by SantoshSrinivas79** [steve-1820/memex#1]
I'm getting the following errors when I try to run this app. Any suggestions?

for `yarn dev`

![Screenshot 2020-09-24 at 12 36 56 PM](https://user-images.githubusercontent.com/1036163/94112347-ee827a80-fe62-11ea-8530-c837a7c6b2d7.png)

for `yarn build`

![Screenshot 2020-09-24 at 12 35 11 PM](https://user-images.githubusercontent.com/1036163/94112363-f6421f00-fe62-11ea-96de-fecf19b4f3b8.png)

**Comment by zpencerq** [comment]
Run `yarn` in `app/packages/graphin/` before running `yarn dev` in the root.

**Comment by SantoshSrinivas79** [comment]
Thank you!
